In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

importing data  set

In [ ]:
dataset = pd.read_csv('Book1.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Germany' 38.0 6100.0]
 ['Spain' 40.0 nan]
 ['Germany' 35.0 58000.0]
 ['France' nan 52000.0]
 ['Spain' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 78.0 23000.0]
 ['Spain' 65.0 54000.0]
 ['Germany' 55.0 56325.0]
 ['France' nan 45000.0]
 ['Spain' 55.0 nan]
 ['Germany' 67.0 nan]
 ['France' 44.0 78500.0]
 ['Spain' 56.0 58000.0]
 ['Germany' 78.0 63000.0]
 ['Spain' 33.0 89000.0]]


In [ ]:
print(y)

['no' 'yes' 'no' 'no' 'yes' 'yes' 'yes' 'no' 'no' 'no' 'yes' 'no' 'no'
 'yes' 'yes' 'yes' 'no' 'no' 'yes']


**Taking care in missing data**

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer( missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Germany' 38.0 6100.0]
 ['Spain' 40.0 57432.8125]
 ['Germany' 35.0 58000.0]
 ['France' 49.588235294117645 52000.0]
 ['Spain' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 78.0 23000.0]
 ['Spain' 65.0 54000.0]
 ['Germany' 55.0 56325.0]
 ['France' 49.588235294117645 45000.0]
 ['Spain' 55.0 57432.8125]
 ['Germany' 67.0 57432.8125]
 ['France' 44.0 78500.0]
 ['Spain' 56.0 58000.0]
 ['Germany' 78.0 63000.0]
 ['Spain' 33.0 89000.0]]


**Encoding categorical deta**

**Encoding independent variable**

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder' , OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 38.0 6100.0]
 [0.0 0.0 1.0 40.0 57432.8125]
 [0.0 1.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 49.588235294117645 52000.0]
 [0.0 0.0 1.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 78.0 23000.0]
 [0.0 0.0 1.0 65.0 54000.0]
 [0.0 1.0 0.0 55.0 56325.0]
 [1.0 0.0 0.0 49.588235294117645 45000.0]
 [0.0 0.0 1.0 55.0 57432.8125]
 [0.0 1.0 0.0 67.0 57432.8125]
 [1.0 0.0 0.0 44.0 78500.0]
 [0.0 0.0 1.0 56.0 58000.0]
 [0.0 1.0 0.0 78.0 63000.0]
 [0.0 0.0 1.0 33.0 89000.0]]


Encoding dependent variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1]


**Splitting data set into the training set and test set**

In [ ]:
!pip install matplotlib-venn

In [ ]:
!apt-get -qq install -y libfluidsynth1

E: Package 'libfluidsynth1' has no installation candidate


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 67.0 57432.8125]
 [0.0 0.0 1.0 40.0 57432.8125]
 [0.0 0.0 1.0 56.0 58000.0]
 [0.0 0.0 1.0 48.0 79000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 55.0 57432.8125]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 33.0 89000.0]
 [0.0 1.0 0.0 78.0 63000.0]
 [1.0 0.0 0.0 78.0 23000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 49.588235294117645 45000.0]
 [0.0 1.0 0.0 55.0 56325.0]
 [0.0 1.0 0.0 35.0 58000.0]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 38.0 6100.0]
 [1.0 0.0 0.0 44.0 78500.0]
 [1.0 0.0 0.0 49.588235294117645 52000.0]
 [0.0 0.0 1.0 65.0 54000.0]]


In [ ]:
print(y_train)

[0 1 1 0 0 1 1 0 1 0 0 0 0 0 1]


In [ ]:
print(y_test)

[0 1 1 1]


**Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.fit_transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 1.0 0.0 -1.2854933710247387 -0.3847140064995999]
 [0.0 1.0 0.0 1.1281643315858896 -0.16611971893956756]
 [0.0 0.0 1.0 -0.6331534514002446 -0.16611971893956756]
 [0.0 0.0 1.0 0.41059041999894597 -0.13000241061717716]
 [0.0 0.0 1.0 -0.11128151570064929 1.207233467765542]
 [0.0 0.0 1.0 -1.4811953469120869 -0.7667814003232339]
 [0.0 0.0 1.0 0.3453564280364966 -0.16611971893956756]
 [1.0 0.0 0.0 -0.3722174835504469 0.7614881749713024]
 [0.0 0.0 1.0 -1.0897913951373903 1.844012457471599]
 [0.0 1.0 0.0 1.8457382431728329 0.18838708423585124]
 [1.0 0.0 0.0 1.8457382431728329 -2.358728874588376]
 [0.0 1.0 0.0 0.019186468224249527 1.461945063647965]
 [1.0 0.0 0.0 -0.007674587289700367 -0.957815097235051]
 [0.0 1.0 0.0 0.3453564280364966 -0.23666289139294167]
 [0.0 1.0 0.0 -0.9593234112124917 -0.13000241061717716]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 -1.1115707891054998 -1.588306349712236]
 [1.0 0.0 0.0 -0.5132582799299802 1.179284016573345]
 [1.0 0.0 0.0 0.043993566851140815 0.16628478029478283]
 [0.0 0.0 1.0 1.5808355021843383 0.24273755284410828]]
