In [4]:
#importing Library

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
#Importing dataset

In [6]:
dataset = pd.read_csv('50Startups.csv')
x= dataset.iloc[:,:-1].values
y= dataset.iloc[:, -1].values

In [10]:
print(x)

[[165349.2 343987.0 442352.242 'New York']
 [736744.44 645435.0 23253.4 'California']
 [423423.44 345353.0 23425.0 'Florida']
 [325353.342 646454.0 242535.0 'New York']
 [423535.3423 4653535.0 464635345.0 'California']
 [342344.24 535353.0 53363.0 'Florida']
 [323523.234 353535.0 3535353.0 'New York']
 [234234.0 353533.0 34343.0 'California']
 [23424.0 353536.0 353535.0 'Florida']
 [234234234.0 64575.0 35353536.0 'New York']
 [234234.0 535353.0 543353.0 'California']
 [3535353.0 646352.0 353534.0 'Florida']
 [53535.0 3466633.0 3434535.0 'New York']
 [3535353.0 3535353.0 0.0 'California']
 [535353.0 525346.0 34535.0 'Florida']
 [23423.0 3453536.0 34534656.0 'New York']
 [353533.0 23423.0 34534534.0 'California']
 [534535.35 353533.0 6365474.0 'Florida']
 [345353.0 534535.35 46436334.0 'New York']
 [353535.0 345353.0 343463463.0 'California']
 [64564.0 353535.0 44363.0 'Florida']
 [575757.0 64564.0 3436363.0 'New York']
 [8686574.0 575757.0 3463435.0 'California']
 [64646.0 8686574.0 363

In [12]:
#Encoding catogorical data

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])], remainder='passthrough')
x= np.array(ct.fit_transform(x))

In [15]:
print(x)

[[0.0 0.0 1.0 165349.2 343987.0 442352.242]
 [1.0 0.0 0.0 736744.44 645435.0 23253.4]
 [0.0 1.0 0.0 423423.44 345353.0 23425.0]
 [0.0 0.0 1.0 325353.342 646454.0 242535.0]
 [1.0 0.0 0.0 423535.3423 4653535.0 464635345.0]
 [0.0 1.0 0.0 342344.24 535353.0 53363.0]
 [0.0 0.0 1.0 323523.234 353535.0 3535353.0]
 [1.0 0.0 0.0 234234.0 353533.0 34343.0]
 [0.0 1.0 0.0 23424.0 353536.0 353535.0]
 [0.0 0.0 1.0 234234234.0 64575.0 35353536.0]
 [1.0 0.0 0.0 234234.0 535353.0 543353.0]
 [0.0 1.0 0.0 3535353.0 646352.0 353534.0]
 [0.0 0.0 1.0 53535.0 3466633.0 3434535.0]
 [1.0 0.0 0.0 3535353.0 3535353.0 0.0]
 [0.0 1.0 0.0 535353.0 525346.0 34535.0]
 [0.0 0.0 1.0 23423.0 3453536.0 34534656.0]
 [1.0 0.0 0.0 353533.0 23423.0 34534534.0]
 [0.0 1.0 0.0 534535.35 353533.0 6365474.0]
 [0.0 0.0 1.0 345353.0 534535.35 46436334.0]
 [1.0 0.0 0.0 353535.0 345353.0 343463463.0]
 [0.0 1.0 0.0 64564.0 353535.0 44363.0]
 [0.0 0.0 1.0 575757.0 64564.0 3436363.0]
 [1.0 0.0 0.0 8686574.0 575757.0 3463435.0]
 [0.0 1.0

In [18]:
#Spliting the data set into training set and test set

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2 , random_state=0)

In [22]:
#Training set

In [24]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [26]:
#Predectig the test set result

In [28]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[6.47e+05 3.54e+05]
 [6.49e+05 1.91e+06]
 [8.02e+06 1.90e+05]
 [8.00e+06 5.53e+06]
 [6.57e+05 1.10e+06]
 [7.75e+06 3.54e+03]
 [1.32e+06 3.36e+05]
 [6.54e+05 6.55e+05]
 [6.57e+05 3.53e+06]
 [7.65e+06 1.97e+04]
 [1.36e+06 3.43e+05]]
